import { createFileRoute } from "@tanstack/react-router";
import Header from "../../components/header";
import Footer from "../../components/footer";
import { loadAllBlogPosts } from "../../utils/blogLoader";

export const Route = createFileRoute("/blog/")({
  component: Blog,
});

export default function Blog() {
  const posts = loadAllBlogPosts();

  return (
    <>
      <Header />
      <main className="zz-blogHubPaper">
        <section className="zz-blogHubIntro" aria-labelledby="blog-hub-title">
          <p className="zz-blogHubKicker">Archive</p>
          <h1 id="blog-hub-title" className="zz-blogHubTitle">
            Writing on engineering, product, and creative process
          </h1>
          <p className="zz-blogHubDeck">
            Notes from building software quickly, fixing messy systems, and
            figuring things out in public.
          </p>
          <p className="zz-authorshipNote">
            All posts here are written by Matthew, not generated by AI.
          </p>
        </section>

        <section className="zz-blogHubGrid" aria-label="All blog posts">
          {posts.map((post) => (
            <article key={post.id} className="zz-blogHubCard">
              <p className="zz-blogHubMeta">
                {formatDate(post.date || new Date().toISOString())}
                {post.readTime ? ` · ${post.readTime}` : ""}
              </p>
              <h2 className="zz-blogHubCardTitle">
                <a href={`/blog/${post.slug}`} className="no-ext zz-link">
                  {post.title}
                </a>
              </h2>
              {post.deck && <p className="zz-blogHubCardDeck">{post.deck}</p>}
              {post.tags && post.tags.length > 0 && (
                <p className="zz-blogHubTags">{post.tags.join(" · ")}</p>
              )}
            </article>
          ))}
        </section>
      </main>
      <Footer />
    </>
  );
}

function formatDate(iso: string) {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
    });
  } catch {
    return iso;
  }
}
